### ISSUE TITLE
Getting messages for WP VIP standards despite setting "phpcs.standard" to "WordPress"

### ISSUE THREAD

**Issue by jerturowetz** [tommcfarlin/phpcs-wpcs-vscode#2]
Among others, phpcs is spitting out the following message:

    [phpcs] get_term_link() is prohibited, please use wpcom_vip_get_term_link() instead.

I didn't expect to get the VIP rule set as my `settings.json` is configured with the normal rule set:

    "phpcs.enable": true,
    "phpcs.standard": "WordPress",

When I comment out `"phpcs.standard" : "WordPress"`, the phpcs messages go away. Obviously I also lose the rest of the phpcs Wordpress standard which is not ideal.

From my terminal when I use `phpcs -i` i get:

    The installed coding standards are MySource, PEAR, PSR1, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra and WordPress-VIP

So I know they're all in there. I'm pretty sure I shouldn't be mucking about by removing just the Wordpress-VIP standard and am assuming I'm doing something wrong with the config (or I've caught an actual bug in which case I'll go bother the wpcs team).

I'm on Windows 10, VSCode.

**Comment by tommcfarlin** [comment]
What you're seeing is correct for:

* The VIP ruleset
* The `phpcs -i` command

You can create a custom ruleset to ignore certain things (such as `wpvom_vip_get_term_link`). The more you work with WordPress-VIP and you're not building _for_ VIP, the more warnings you'll see like this.

Everything is working as expected. You may be better off with either the `WordPress` rules or a custom ruleset.

**Comment by jerturowetz** [comment]
I thought I had set the rules to `Wordpress` hence the ticket. I'm wondering what I'm doing wrong.

**Comment by jerturowetz** [comment]
Sorry for the confusion. I was assuming that the `Wordpress` ruleset didn't include `Wordpress-VIP` by default. It does, and I missed the note about it in the manual: [Rulesets - Standards subsets](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards#user-content-standards-subsets).

Setting `phpcs.standard` to `WordPress-Core` or `WordPress-Extra` gets all the good stuff loaded without the VIP extras.
