### ISSUE TITLE
Is it possible to Format / Indent code in WordPress coding standards too?

### ISSUE THREAD

**Issue by pablo-sg-pacheco** [tommcfarlin/phpcs-wpcs-vscode#3]
Php Code Sniffer can format / indent code too.
This is the command to do that:
`phpcbf --standard=WordPress`

However, in visual studio code, I didn't manage to do that. I was only able to see warnings on my code.
Is it possible to format / indent code inside vscode too?

Reference:
https://deluxeblogtips.com/installing-wordpress-coding-standards-windows/

**Comment by tommcfarlin** [comment]
To be clear, are you asking me for how to get something working based on the the reference you've provided?

**Comment by pablo-sg-pacheco** [comment]
Hi,

Sorry if my message sounded rude. That's not my intention.
I just wanted to ask if you know how to format code using WordPress coding standards somehow

**Comment by tommcfarlin** [comment]
The best advice I can give is to follow the guide listed [here](https://github.com/tommcfarlin/phpcs-wpcs-vscode) in this repository. If that doesn't work, you may have success reading [this post](https://tommcfarlin.com/php-codesniffer-in-visual-studio-code/) as well.

Unfortunately, I can't offer anything beyond that.

**Comment by pablo-sg-pacheco** [comment]
Ok, thanks
